---
  - src: git@github.com:AlexeySetevoi/ansible-clickhouse.git
    scm: git
    version: "1.13"
    name: clickhouse 

  - src: git@github.com:drumlast/vector-role.git
    scm: git
    version: main
    name: vector_role

  - src: git@github.com:drumlast/lighthouse-role.git
    scm: git
    version: "v1.0.0"
    name: lighthouse_role