---
# Main installation actions
# Based on official ClickHouse docs for Debian/Ubuntu:
# https://clickhouse.com/docs/en/install#installation-on-debianubuntu

- name: Install prerequisites
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
    state: present
    update_cache: true
  become: true
  tags: [install]

- name: Ensure keyrings directory exists
  ansible.builtin.file:
    path: /usr/share/keyrings
    state: directory
    mode: '0755'
  become: true
  tags: [install]

- name: Download ClickHouse LTS repo key (official)
  ansible.builtin.get_url:
    url: https://packages.clickhouse.com/rpm/lts/repodata/repomd.xml.key
    dest: /usr/share/keyrings/clickhouse-keyring.gpg
    mode: '0644'
    force: true
  become: true
  tags: [install]

- name: Add ClickHouse apt repo (LTS)
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/clickhouse-keyring.gpg arch={{ ansible_architecture }}] https://packages.clickhouse.com/deb lts main"
    state: present
    filename: clickhouse
  become: true
  tags: [install]

- name: Install ClickHouse packages (fixed version)
  ansible.builtin.apt:
    name: "{{ clickhouse_package | map('regex_replace', '$', '=' + clickhouse_version) | list }}"
    state: present
    update_cache: true
  become: true
  when: clickhouse_version != 'latest'
  tags: [install]

- name: Install ClickHouse packages (latest)
  ansible.builtin.apt:
    name: "{{ clickhouse_package }}"
    state: "{{ clickhouse_version }}"
    update_cache: true
  become: true
  when: clickhouse_version == 'latest'
  tags: [install]

- name: Hold specified version during APT upgrade | Package installation
  become: true
  copy:
    dest: "/etc/apt/preferences.d/fixed-{{ item }}"
    content: |
      Package: {{ item }}
      Pin: release a=now
      Pin-Priority: 1001
  loop: "{{ clickhouse_package }}"