---
# Install ClickHouse on Ubuntu 24.04 using stable repo (без GPG проверки)

- name: Install prerequisites
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
    state: present
    update_cache: true
  become: true
  tags: [install]

- name: Add ClickHouse apt repo (без проверки подписи)
  ansible.builtin.apt_repository:
    repo: "deb [trusted=yes] https://packages.clickhouse.com/deb stable main"
    state: present
    filename: clickhouse
  become: true
  tags: [install]

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
  become: true
  tags: [install]

- name: Install ClickHouse packages (fixed version)
  ansible.builtin.apt:
    name: "{{ clickhouse_package | map('regex_replace', '$', '=' + clickhouse_version) | list }}"
    state: present
  become: true
  when: clickhouse_version != 'latest'
  tags: [install]

- name: Install ClickHouse packages (latest)
  ansible.builtin.apt:
    name: "{{ clickhouse_package }}"
    state: latest
  become: true
  when: clickhouse_version == 'latest'
  tags: [install]

- name: Hold specified version during APT upgrade | Package installation
  become: true
  copy:
    dest: "/etc/apt/preferences.d/fixed-{{ item }}"
    content: |
      Package: {{ item }}
      Pin: release a=now
      Pin-Priority: 1001
  loop: "{{ clickhouse_package }}"
  tags: [install]