---
# Main installation actions
# https://clickhouse.com/docs/en/getting-started/#installation

- name: Ensure keyrings directory exists
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'
  become: true
  tags: [install]

- name: Install by APT | Download ClickHouse repo key (LTS)
  ansible.builtin.get_url:
    url: https://packages.clickhouse.com/deb/lts/Release.gpg
    dest: /etc/apt/keyrings/clickhouse.gpg
    mode: '0644'
  become: true
  tags: [install]

- name: Install by APT | Remove old repo
  ansible.builtin.apt_repository:
    repo: "{{ clickhouse_repo_old }}"
    state: absent
  become: true
  when: clickhouse_repo_old is defined
  tags: [install]

- name: Install by APT | Repo installation (LTS)
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/clickhouse.gpg] https://packages.clickhouse.com/deb lts main"
    state: present
    filename: clickhouse
  become: true
  tags: [install]

- name: Install by APT | Package installation (fixed version)
  ansible.builtin.apt:
    name: "{{ clickhouse_package | map('regex_replace', '$', '=' + clickhouse_version) | list }}"
    state: present
    update_cache: true
  become: true
  when: clickhouse_version != 'latest'
  tags: [install]

- name: Install by APT | Package installation (latest)
  ansible.builtin.apt:
    name: "{{ clickhouse_package }}"
    state: "{{ clickhouse_version }}"
    update_cache: true
  become: true
  when: clickhouse_version == 'latest'
  tags: [install]

- name: Hold specified version during APT upgrade | Package installation
  become: true
  copy:
    dest: "/etc/apt/preferences.d/fixed-{{ item }}"
    content: |
      Package: {{ item }}
      Pin: release a=now
      Pin-Priority: 1001
  loop: "{{ clickhouse_package }}"