---
# Install ClickHouse on Ubuntu 24.04 (без GPG проверки, через trusted=yes)

- name: Install prerequisites
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
    state: present
    update_cache: true
  become: true
  tags: [install]

- name: Add ClickHouse apt repo (trusted=yes)
  ansible.builtin.copy:
    dest: /etc/apt/sources.list.d/clickhouse.list
    content: |
      deb [trusted=yes] https://packages.clickhouse.com/deb stable main
  mode: '0644'
  owner: root
  group: root
  become: true
  tags: [install]

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
  become: true
  tags: [install]

- name: Install ClickHouse packages (fixed version)
  ansible.builtin.apt:
    name: "{{ clickhouse_package | map('regex_replace', '$', '=' + clickhouse_version) | list }}"
    state: present
  become: true
  when: clickhouse_version != 'latest'
  tags: [install]

- name: Install ClickHouse packages (latest)
  ansible.builtin.apt:
    name: "{{ clickhouse_package }}"
    state: latest
  become: true
  when: clickhouse_version == 'latest'
  tags: [install]
