---
# Main installation actions for ClickHouse (Ubuntu 24.04, stable repo)

- name: Install prerequisites
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
    state: present
    update_cache: true
  become: true
  tags: [install]

- name: Ensure keyrings directory exists
  ansible.builtin.file:
    path: /usr/share/keyrings
    state: directory
    mode: '0755'
  become: true
  tags: [install]

- name: Download ClickHouse stable repo key
  ansible.builtin.get_url:
    url: https://packages.clickhouse.com/CLICKHOUSE-KEY.GPG
    dest: /usr/share/keyrings/clickhouse-stable.gpg
    mode: '0644'
    force: true
  become: true
  tags: [install]

- name: Add ClickHouse apt repo (stable)
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/clickhouse-stable.gpg arch={{ ansible_architecture }}] https://packages.clickhouse.com/deb stable main"
    state: present
    filename: clickhouse
  become: true
  tags: [install]

- name: Install ClickHouse packages (fixed version)
  ansible.builtin.apt:
    name: "{{ clickhouse_package | map('regex_replace', '$', '=' + clickhouse_version) | list }}"
    state: present
    update_cache: true
  become: true
  when: clickhouse_version != 'latest'
  tags: [install]

- name: Install ClickHouse packages (latest)
  ansible.builtin.apt:
    name: "{{ clickhouse_package }}"
    state: "{{ clickhouse_version }}"
    update_cache: true
  become: true
  when: clickhouse_version == 'latest'
  tags: [install]

- name: Hold specified version during APT upgrade | Package installation
  become: true
  copy:
    dest: "/etc/apt/preferences.d/fixed-{{ item }}"
    content: |
      Package: {{ item }}
      Pin: release a=now
      Pin-Priority: 1001
  loop: "{{ clickhouse_package }}"