---
dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: vector-ubuntu
    image: ubuntu:latest
    command: /sbin/init
    privileged: true
    pre_build_image: true

  - name: vector-oracle
    image: oraclelinux:8
    command: /sbin/init
    privileged: true
    pre_build_image: true

provisioner:
  name: ansible
  config_options:
    defaults:
      remote_tmp: /tmp/.ansible/tmp

verifier:
  name: ansible
