---
dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: ubuntu-latest
    image: ubuntu:latest
    privileged: true
    command: /sbin/init
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /tmp:/tmp
    pre_build_image: true

  - name: oraclelinux-8
    image: oraclelinux:8
    privileged: true
    command: /sbin/init
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /tmp:/tmp
    pre_build_image: true

provisioner:
  name: ansible
  lint: |
    yamllint .
    ansible-lint .
  playbooks:
    converge: converge.yml

verifier:
  name: ansible
  lint: |
    yamllint .
    ansible-lint .
    