---
driver:
  name: docker

platforms:
  - name: instance-ubuntu
    image: ubuntu:latest
    pre_build_image: true
  - name: instance-oraclelinux
    image: oraclelinux:8
    pre_build_image: true

provisioner:
  name: ansible
  playbooks:
    converge: converge.yml

verifier:
  name: ansible