---
dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: ubuntu-latest
    image: ubuntu:latest
    privileged: true
    pre_build_image: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /tmp/ansible:/root/.ansible/tmp

  - name: oraclelinux-8
    image: oraclelinux:8
    privileged: true
    pre_build_image: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /tmp/ansible:/root/.ansible/tmp

provisioner:
  name: ansible
  config_options:
    defaults:
      host_key_checking: False
      retry_files_enabled: False
  playbooks:
    converge: converge.yml

verifier:
  name: ansible
