---
dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: vector-ubuntu
    image: docker.io/library/ubuntu:22.04
    pre_build_image: true
    command: sleep infinity      # держит контейнер «живым»
    tty: true
    privileged: true             # можно убрать, если не нужен

  - name: vector-oracle
    image: docker.io/library/oraclelinux:8
    pre_build_image: true
    command: sleep infinity
    tty: true
    privileged: true

provisioner:
  name: ansible
  playbooks:
    converge: converge.yml
  config_options:
    defaults:
      remote_tmp: /tmp/.ansible/tmp
  env:
    ANSIBLE_REMOTE_TMP: /tmp/.ansible/tmp

verifier:
  name: ansible

scenario:
  name: default
  test_sequence:
    - destroy
    - create
    - converge
    - verify
    - destroy
