---
dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: ubuntu-latest
    image: ubuntu:latest
    privileged: true
    pre_build_image: true
  - name: oraclelinux-8
    image: oraclelinux:8
    privileged: true
    pre_build_image: true

provisioner:
  name: ansible
  config_options:
    defaults:
      # фикс ошибки "Failed to create temporary directory"
      remote_tmp: /tmp/.ansible/tmp
      host_key_checking: false
  inventory:
    host_vars: {}
    group_vars: {}
  playbooks:
    converge: converge.yml
  lint: |
    yamllint .
    ansible-lint .

verifier:
  name: ansible
  lint: |
    yamllint .
    ansible-lint .
