---
dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: vector-ubuntu
    image: docker.io/library/ubuntu:latest
    command: /sbin/init
    privileged: true
    pre_build_image: true
    tty: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro

  - name: vector-oracle
    image: docker.io/library/oraclelinux:8
    command: /sbin/init
    privileged: true
    pre_build_image: true
    tty: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro

provisioner:
  name: ansible
  config_options:
    defaults:
      remote_tmp: /tmp/.ansible/tmp

verifier:
  name: ansible
