---
dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: vector-ubuntu
    image: ubuntu:latest
    command: /sbin/init
    privileged: true
    tty: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro

  - name: vector-oracle
    image: oraclelinux:8
    command: /sbin/init
    privileged: true
    tty: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro

provisioner:
  name: ansible

verifier:
  name: ansible
