---
dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: ubuntu-latest
    image: ubuntu:latest
    privileged: true
    pre_build_image: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /tmp:/tmp

  - name: oraclelinux-8
    image: oraclelinux:8
    privileged: true
    pre_build_image: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /tmp:/tmp

provisioner:
  name: ansible
  playbooks:
    converge: converge.yml

verifier:
  name: ansible
