---
dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: test-ubuntu
    image: ubuntu:latest
    command: sleep infinity
    privileged: true

provisioner:
  name: ansible

verifier:
  name: ansible
