---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Ensure vector package is installed
      ansible.builtin.package:
        name: vector
        state: present
      check_mode: true
      register: result_pkg
      failed_when: result_pkg is failed

    - name: Ensure vector service is running
      ansible.builtin.service:
        name: vector
        state: started
        enabled: true
      check_mode: true
      register: result_svc
      failed_when: result_svc is failed

    - name: Ensure vector config exists
      ansible.builtin.stat:
        path: /etc/vector/vector.toml
      register: vector_cfg
      failed_when: not vector_cfg.stat.exists

    - name: Validate vector config
      ansible.builtin.command: >
        vector validate --no-environment --config-toml /etc/vector/vector.toml
      register: vector_validate
      changed_when: false
      failed_when: vector_validate.rc != 0
