---
- name: Verify Vector installation
  hosts: all
  tasks:
    - name: Check vector binary exists
      ansible.builtin.command: which vector
      register: vector_bin
      changed_when: false
      failed_when: vector_bin.rc != 0

    - name: Check vector service is running
      ansible.builtin.shell: systemctl is-active vector
      register: vector_service
      changed_when: false
      failed_when: vector_service.stdout.strip() != "active"
