---
- name: Verify Vector installation
  hosts: all
  gather_facts: false
  tasks:
    - name: Check vector binary exists
      ansible.builtin.command: which vector
      register: vector_bin
      changed_when: false

    - name: Assert vector is installed
      ansible.builtin.assert:
        that:
          - vector_bin.rc == 0

    - name: Check vector service config
      ansible.builtin.stat:
        path: /etc/vector/vector.toml
      register: vector_conf

    - name: Assert config exists
      ansible.builtin.assert:
        that:
          - vector_conf.stat.exists
