---
- name: Verify Vector installation
  hosts: all
  tasks:
    - name: Ensure vector binary exists
      ansible.builtin.command: vector --version
      register: vector_version
      changed_when: false

    - name: Check vector config exists
      ansible.builtin.stat:
        path: /etc/vector/vector.yaml
      register: vector_config

    - name: Assert vector config is present
      ansible.builtin.assert:
        that:
          - vector_config.stat.exists

    - name: Assert vector service is running
      ansible.builtin.service_facts:

    - name: Ensure vector service is active
      ansible.builtin.assert:
        that:
          - "'vector' in services"
          - "services['vector'].state == 'running'"
